# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-long-audio-transcription-es
dependencies:
  - python=3.9
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - ffmpeg
  - libsndfile
  - pip:
    - torch
    - transformers
    - youtube-dl
    - huggingsound
    # - -r file:requirements.txt